### PR TITLE
Fix settings E::ts() usage (and update the civix file).

### PR DESCRIPTION
**Pull request by mlutfy**
Fixes the `ts()` usage for the extension settings. The code was sending a variable in `ts()` and while that could technically work, it is not a recommended gettext practice because the string cannot be extracted in context.

I also had to regenerate the civix file, so that we can use `E::ts('foo')` instead of `ts('foo', ['domain' => 'au.com.agileware.civiquickbooks']);`

References:

* https://docs.civicrm.org/dev/en/latest/translation/extensions/
* https://docs.civicrm.org/dev/en/latest/translation/#avoid-variables-inside-strings

### CODE REVIEW

**Comment by jusfreeman** [comment]
Thanks for the PR @mlutfy

**Comment by agileware-fj** [comment]
Civix file regeneration is fine, but I'm not sure if translating the strings directly in the settings hook is a good idea - as we really want to do this when generating the form output so it's translated for the current user.

Would prefer to do the translation on the variable and add a list of static translation strings for the extraction tools.

**Comment by mlutfy** [comment]
There is one exception (menu items), but otherwise, all CiviCRM strings (and any software using Gettext) are translated where they are found, not at the UI layer. I'm not sure I understand the issue with putting it in the settings hook?

**Comment by agileware-fj** [comment]
Sorry, I was under the (apparently mis-) apprehension that the config hook was run occasionally rather than every bootstrap.  Withdraw objection :)

**Pull request merged**
